# This is a basic workflow to help you get started with Actions

name: dependant workflow
on:
  workflow_run:
    workflows: ["manual trigger"]
    branches:
      - release-**
    types:
      - completed
  workflow_dispatch:
jobs:

  depandantjob:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          pwd
          ls

