name: Deploy to int Sandbox

on:
  pull_request:
    types: [closed]
    branches:
      - integration

jobs:
  validate_merge_to_integration:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - name: checkout
        if: github.event.pull_request.merged
        uses: actions/checkout@v1

     
  deploy-to-qa:      
    runs-on: ubuntu-latest
    needs: validate_merge_to_integration
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
