name: Deploy to Integration Sandbox
on:
  push:
    branches:
      - integration
jobs:
  deploy-on-int:     
    runs-on: ubuntu-latest
    steps:
      - name: Install Salesforce CLI
        run: |
          echo "welcome "
