name: Run_Apex_on_QA-Sandbox
on:
  pull_request:
    branches: 
      - release-**
    types: [opened, synchronize, reopened]
jobs:
  run-unit-test-on-qa:
    runs-on: ubuntu-latest
    steps:
      - name: test for this Apex TEST QA
        run: |
          echo "this is test file for APEX"
       
     
     
