name: Run unit tests on int Sandbox

on: 
  pull_request:
    branches:
      - integration
    paths:
      - '.github/workflows/**'
      - 'force-app/**'

jobs:

  run-unit-tests-on-qa:     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
