name: Run unit tests on int Sandbox

on:
  push:
    branches: [ integration ]   
    paths:
      - '.github/workflows/**'
      - 'force-app/**'

jobs:
  run-unit-tests-on-int:     
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout source code
          uses: actions/checkout@v2

      # Runs a single command using the runners shell
        - name: Run a one-line script
          run: echo Hello, world!
