name: Run unit tests on QA Sandbox
on: 
  push:
    branches:
      - release-**
    paths:
      - '.github/workflows/**'
      - 'force-app/**'

jobs:
  run-unit-tests-on-qa:     
    runs-on: ubuntu-latest
    steps:
    - name: Install Salesforce CLI
      run: echo "test deploy"
